#!/bin/bash
set -eo pipefail

#
# Before calling this script, set the following environent variables:
#
#   - CI_BRANCH: the branch being tested
#   - CI_BUILD_NUMBER: monotonically increasing build counter
#   - PR_NUMBER: pull request number (if job is from a pull request)
#
# Optionally, instead of setting PR_NUMBER, CI_PULL_REQUEST may
# be set instead. CI_PULL_REQUEST is the URL of the current pull
# request. It is assumed that this URL ends with "/PR_NUMBER".
#


# If variables were not passed in from the caller, then
# fill in values from CircleCI environment variables, if set.
CI_BRANCH=${CI_BRANCH:-$CIRCLE_BRANCH}
CI_BUILD_NUMBER=${CI_BUILD_NUMBER:-$CIRCLE_BUILD_NUM}
# Circle sets both $CIRCLE_PULL_REQUEST and $CI_PULL_REQUEST.
PR_NUMBER=${PR_NUMBER:-$CI_PULL_REQUEST}
PR_NUMBER=${PR_NUMBER##*/}

# Set up BASH_ENV if it was not set for us.
BASH_ENV=${BASH_ENV:-$HOME/.bashrc}

# Provide a default email address
GIT_EMAIL=${GIT_EMAIL:-ci-bot@pantheon.io}

# Avoid ssh prompting when connecting to new ssh hosts
mkdir -p $HOME/.ssh && echo "StrictHostKeyChecking no" >> "$HOME/.ssh/config"

# Configure the GitHub Oauth token if it is available
if [ -n "$GITHUB_TOKEN" ] ; then
  composer -n config --global github-oauth.github.com $GITHUB_TOKEN
fi

# Set up our default git config settings.
git config --global user.email "$GIT_EMAIL"
git config --global user.name "CI Bot"
git config --global core.fileMode false

# Set up environment variables

# By default, we will make the environment name after the circle build number.
DEFAULT_ENV=ci-$CI_BUILD_NUMBER

# If there is a PR number provided, though, then we will use it instead.
if [[ -n ${PR_NUMBER} ]] ; then
  DEFAULT_ENV="pr-${PR_NUMBER}"
fi

#=====================================================================================================================
# EXPORT needed environment variables
#
# Circle CI 2.0 does not yet expand environment variables so they have to be manually EXPORTed
# Once environment variables can be expanded this section can be removed
# See: https://discuss.circleci.com/t/unclear-how-to-work-with-user-variables-circleci-provided-env-variables/12810/11
# See: https://discuss.circleci.com/t/environment-variable-expansion-in-working-directory/11322
# See: https://discuss.circleci.com/t/circle-2-0-global-environment-variables/8681
#=====================================================================================================================
(
  echo 'export PATH=$PATH:$HOME/bin'
  echo "export PR_NUMBER=$PR_NUMBER"
  echo "export CI_BRANCH=$CI_BRANCH"
  echo "export CI_BUILD_NUMBER=$CI_BUILD_NUMBER"
  echo "export DEFAULT_ENV='$DEFAULT_ENV'"
  echo 'export TERMINUS_HIDE_UPDATE_MESSAGE=1'
  echo 'export TERMINUS_ENV=${TERMINUS_ENV:-$DEFAULT_ENV}'
) >> $BASH_ENV
source $BASH_ENV

# Re-install the Terminus Build Tools plugin if requested
if [ -n $BUILD_TOOLS_VERSION ] && [ "$BUILD_TOOLS_VERSION" <> 'dev-master' ]; then
  echo "Install Terminus Build Tools Plugin version $BUILD_TOOLS_VERSION"
  rm -rf ${TERMINUS_PLUGINS_DIR:-~/.terminus/plugins}/terminus-build-tools-plugin
  composer -n create-project -d ${TERMINUS_PLUGINS_DIR:-~/.terminus/plugins} pantheon-systems/terminus-build-tools-plugin:$BUILD_TOOLS_VERSION
fi
