#!/bin/bash
set -eo pipefail

#
# Before calling this script, set the following environent variables:
#
#   - CI_BRANCH: the branch being tested
#   - CI_BUILD_NUMBER: monotonically increasing build counter
#   - PR_NUMBER: pull request number (if job is from a pull request)
#
# Optionally:
#
#   - CI_PULL_REQUEST: URL to the current pull request; used to set PR_NUMBER
#   - DEFAULT_SITE: name of the repository; used to set TERMINUS_SITE
#
# Note that any environment variable given above is not set, then
# it will be assigned its value from the corresponding CircleCI
# environment variable.
#
CI_BRANCH=${CI_BRANCH:-$CIRCLE_BRANCH}
CI_BUILD_NUMBER=${CI_BUILD_NUMBER:-$CIRCLE_BUILD_NUM}

# Circle sets both $CIRCLE_PULL_REQUEST and $CI_PULL_REQUEST.
PR_NUMBER=${PR_NUMBER:-$CI_PULL_REQUEST}
PR_NUMBER=${PR_NUMBER##*/}

# Set up BASH_ENV if it was not set for us.
BASH_ENV=${BASH_ENV:-$HOME/.bashrc}

# Provide a default email address
GIT_EMAIL=${GIT_EMAIL:-ci-bot@pantheon.io}

# We will also set the default site name to be the same as the repository name.
DEFAULT_SITE=${DEFAULT_SITE:-$CIRCLE_PROJECT_REPONAME}

# By default, we will make the environment name after the circle build number.
DEFAULT_ENV=ci-$CI_BUILD_NUMBER

# If there is a PR number provided, though, then we will use it instead.
if [[ -n ${PR_NUMBER} ]] ; then
  DEFAULT_ENV="pr-${PR_NUMBER}"
fi

CI_BUILD_URL=${CI_BUILD_URL:-$CIRCLE_BUILD_URL}
CI_NODE_INDEX=${CI_NODE_INDEX:-$CIRCLE_NODE_INDEX}
CI_PR_URL=${CI_PR_URL:-$CIRCLE_PULL_REQUEST}
CI_PROJECT_USERNAME=${CI_PROJECT_USERNAME:-$CIRCLE_PROJECT_USERNAME}
CI_PROJECT_REPONAME=${CI_PROJECT_REPONAME:-$CIRCLE_PROJECT_REPONAME}

#=====================================================================================================================
# EXPORT needed environment variables
#
# Circle CI 2.0 does not yet expand environment variables so they have to be manually EXPORTed
# Once environment variables can be expanded this section can be removed
# See: https://discuss.circleci.com/t/unclear-how-to-work-with-user-variables-circleci-provided-env-variables/12810/11
# See: https://discuss.circleci.com/t/environment-variable-expansion-in-working-directory/11322
# See: https://discuss.circleci.com/t/circle-2-0-global-environment-variables/8681
# Bitbucket has similar issues:
# https://bitbucket.org/site/master/issues/18262/feature-request-pipeline-command-to-modify
#=====================================================================================================================
(
  echo 'export PATH=$PATH:$HOME/bin'
  echo "export PR_NUMBER=$PR_NUMBER"
  echo "export CI_BRANCH=$(echo $CI_BRANCH | grep -v '"'^\(master\|[0-9]\+.x\)$'"')"
  echo "export CI_BUILD_NUMBER=$CI_BUILD_NUMBER"
  echo "export DEFAULT_SITE='$DEFAULT_SITE'"
  echo "export CI_NODE_INDEX='$CI_NODE_INDEX'"
  echo "export CI_BUILD_URL='$CI_BUILD_URL'"
  echo "export CI_PR_URL='$CI_PR_URL'"
  echo "export CI_PROJECT_USERNAME='$CI_PROJECT_USERNAME'"
  echo "export CI_PROJECT_REPONAME='$CI_PROJECT_REPONAME'"
  echo "export DEFAULT_ENV='$DEFAULT_ENV'"
  echo 'export TERMINUS_HIDE_UPDATE_MESSAGE=1'
  echo 'export TERMINUS_SITE=${TERMINUS_SITE:-$DEFAULT_SITE}'
  echo 'export TERMINUS_ENV=${TERMINUS_ENV:-$DEFAULT_ENV}'
  # TODO: Reconcile with environment variables set by build:project:create
  echo 'export BEHAT_ADMIN_PASSWORD=$(openssl rand -base64 24)'
  echo 'export BEHAT_ADMIN_USERNAME=pantheon-ci-testing-$CI_BUILD_NUMBER'
  echo 'export BEHAT_ADMIN_EMAIL=no-reply+ci-$CI_BUILD_NUMBER@getpantheon.com'
  echo "export MULTIDEV_SITE_URL='https://${TERMINUS_ENV:-$DEFAULT_ENV}-${TERMINUS_SITE:-$DEFAULT_SITE}.pantheonsite.io/'"
  echo "export LIVE_SITE_URL='https://live-${TERMINUS_SITE:-$DEFAULT_SITE}.pantheonsite.io/'"
  echo "export ARTIFACTS_DIR='artifacts'" >> $BASH_ENV
  echo "export ARTIFACTS_FULL_DIR='/tmp/artifacts'" >> $BASH_ENV
  echo "export ARTIFACTS_DIR_URL='${CI_BUILD_URL}/artifacts/${CI_NODE_INDEX}/artifacts'" >> $BASH_ENV
) >> $BASH_ENV
source $BASH_ENV

echo 'Contents of BASH_ENV:'
cat $BASH_ENV
echo

# Avoid ssh prompting when connecting to new ssh hosts
mkdir -p $HOME/.ssh && echo "StrictHostKeyChecking no" >> "$HOME/.ssh/config"

# Create the artifacts directory if needed
if [ ! -d "$ARTIFACTS_FULL_DIR" ]; then
  mkdir -p $ARTIFACTS_FULL_DIR
fi

# Configure the GitHub Oauth token if it is available
if [ -n "$GITHUB_TOKEN" ] && [ -x "$(command -v composer)" ]; then
  composer -n config --global github-oauth.github.com $GITHUB_TOKEN
fi

# Set up our default git config settings if git is available.
if [ -x "$(command -v git)" ]; then
  git config --global user.email "${GIT_EMAIL:-no-reply+ci-$CI_BUILD_NUMBER@getpantheon.com}"
  git config --global user.name "CI Bot"
  git config --global core.fileMode false
fi

# Re-install the Terminus Build Tools plugin if requested and Composer is available
if [ -x "$(command -v composer)" ] && [ -n $BUILD_TOOLS_VERSION ] && [ "$BUILD_TOOLS_VERSION" <> 'dev-master' ]; then
  echo "Install Terminus Build Tools Plugin version $BUILD_TOOLS_VERSION"
  rm -rf ${TERMINUS_PLUGINS_DIR:-~/.terminus/plugins}/terminus-build-tools-plugin
  composer -n create-project -d ${TERMINUS_PLUGINS_DIR:-~/.terminus/plugins} pantheon-systems/terminus-build-tools-plugin:$BUILD_TOOLS_VERSION
fi
