name: Docker Build Tools Image (Build and Push)

permissions:
  contents: read

on:
  push:
    branches:
      - '9.x'
jobs:
  docker-build:
    runs-on: ubuntu-latest
    name: Build and push ${{ matrix.php-versions }} Docker image
    strategy:
      matrix:
        php-versions: ['8.2', '8.3', '8.4']
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480 # v1.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9 # v1.7.0
      -
        name: Login to DockerHub
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Quay
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # v1.14.1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a # v2.10.0
        with:
          context: .
          push: true
          tags: |
            pantheonpublic/build-tools-ci:9.x-php${{ matrix.php-versions }}
            quay.io/pantheon-public/build-tools-ci:9.x-php${{ matrix.php-versions }}
          build-args: |
            PHPVERSION=${{ matrix.php-versions }}
